name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: windows-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - run: npm ci

      - name: build and release Electron app
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
